on:
  push:
    branches:
      - develop
name: Build android
jobs:
  build-apk:
    name: Build and deploy to test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install java
        uses: actions/setup-java@v3
        with:
          java-version: "17.0.1"
          distribution: "oracle"

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.2'
          channel: "stable"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          working-directory: 'android'
          bundler-cache: true

      - name: Get dependencies
        run: |
          flutter pub get

      - name: Service account key
        run: echo "${{ secrets.SA_FIREBASE }}" | base64 -d > android/fastlane/service-account-key.json

      - name: Deploy to app distrib
        uses: maierj/fastlane-action@v3.0.0
        env:
          FIREBASE_APP_ID_ANDROID: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
        with:
          lane: 'deployToAppDistrib'
          subdirectory: "android"