on:
  push:
    branches:
      - develop
name: Build android
jobs:
  build-apk:
    name: Build android apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install java
        uses: actions/setup-java@v3
        with:
          java-version: "17.0.1"
          distribution: "oracle"

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.2'
          channel: "stable"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Copy play store upload key to app
        run: echo "${{vars.PLAY_STORE_UPLOAD_KEY}}" | base64 -d > android/fastlane/play-store-credentials.json

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          working-directory: 'android'
          bundler-cache: true

      - name: Get dependencies
        run: |
          flutter pub get

      - name: Build app bundle release
        uses: maierj/fastlane-action@v3.0.0
        env:
          ANDROID_STORE_PASSWORD: ${{secrets.ANDROID_STORE_PASSWORD}}
          ANDROID_KEY_ALIAS: ${{secrets.ANDROID_KEY_ALIAS}}
        with:
          lane: 'beta'
          subdirectory: "android"

      #      - name: Service account key
      #        run: echo "${{ secrets.SA_FIREBASE }}" | base64 -d > service-account-key.json

      #      - name: upload artifact to Firebase App Distribution
      #        uses: wzieba/Firebase-Distribution-Github-Action@v1
      #        with:
      #          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
      #          serviceCredentialsFile: service-account-key.json
      #          groups: testers
      #          file: app/release/app-release.aab

      - name: Deploy to playstore
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'deploy'
          subdirectory: "android"