on:
  push:
    branches:
      - 'feat/*'
      - 'fix/*'
      - 'release/*'
      - 'chore/*'

name: Test coverage
jobs:
  test-coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install java
        uses: actions/setup-java@v3
        with:
          java-version: "17.0.1"
          distribution: "oracle"

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.2'
          channel: "stable"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Get dependencies
        run: |
          flutter pub get

      - name: Flutter test coverage
        run: |
          flutter test --machine --coverage > tests.output

      - name: SonarQube  scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: ${{ vars.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}