on:
  push:
    branches:
      - 'feat/*'
      - 'fix/*'
      - 'release/*'
      - 'chore/*'

name: Test coverage
env:
  flutter_version: 3.13.2
  sonar_scanner_version: 5.0.1.3006
  SONARQUBE_HOST: ${{vars.SONARQUBE_HOST}}
jobs:
  test-coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install java
        uses: actions/setup-java@v3
        with:
          java-version: "17.0.1"
          distribution: "oracle"

      - name: Install sonar-scanner
        run: |
          wget --output-document=sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$sonar_scanner_version-linux.zip
          unzip sonar-scanner.zip
          echo "sonar-scanner-$sonar_scanner_version-linux/bin" >> $GITHUB_PATH

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: flutter_version
          channel: "stable"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Get dependencies
        run: |
          flutter pub get

      - name: Flutter test coverage
        run: |
          flutter test --machine --coverage > tests.output
          sonar-scanner -Dsonar.host.url=$SONARQUBE_HOST -Dsonar.login=${{secrets.SONARQUBE_TOKEN }} -Dsonar.projectKey=${{ secrets.PROJECT_KEY }}
