on:
  push:
    branches:
      - 'feat/*'
      - 'fix/*'
      - 'release/*'
      - 'chore/*'

name: Test coverage
env:
  SC_VERSION: 5.0.1.3006
  SONARQUBE_HOST: ${{vars.SONARQUBE_HOST}}
  SONARQUBE_TOKEN: ${{secrets.SONARQUBE_TOKEN }}
  PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
jobs:
  Setup-env:
    name: Setup env
    runs-on: ubuntu-latest
    steps:
      - name: Install sonar-scanner
        run: |
          wget --output-document=sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SC_VERSION-linux.zip
          unzip sonar-scanner.zip
          echo "sonar-scanner-$SC_VERSION-linux/bin" >> $GITHUB_PATH

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

  flutter-coverage:
    name: flutter test coverage
    runs-on: ubuntu-latest
    needs: Setup-env
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sonar file
        run: |
          echo "${{ secrets.SONAR_PROJECT_FILE }}" > sonar-project.properties

      - name: Get dependencies
        run: |
          needs.Setup-env.flutter pub get

      - name: Flutter test coverage
        run: |
          needs.Setup-env.flutter test --machine --coverage > tests.output
          needs.Setup-env.sonar-scanner
